---
title: "ABCD_OHBM_PFN_Analyses"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width=250)
library(tidyr)
library(dplyr)
library(ggplot2)
library(lsr)
library(lme4)
library(lmerTest)
```


# First load in the spatial extent of each PFN (they're in order, 1-17)
# Then merge with the same datasets as above (NIH toolbox, trauma, etc.)
```{r}
pfn_sizes <- read.csv("/Users/ariellekeller/Documents/Kellernet_PrelimAnalysis/All_PFN_sizes.csv")
nihtb<-read.table("/Users/ariellekeller/Documents/Kellernet_PrelimAnalysis/NihTB/abcd_tbss01.txt",header=TRUE)
nihtb.baseline<-nihtb[nihtb$eventname=="baseline_year_1_arm_1",]
merged.data1 <- merge(pfn_sizes,nihtb.baseline,by="subjectkey")
lmt<-read.table("/Users/ariellekeller/Documents/Kellernet_PrelimAnalysis/Thomp/lmtp201.txt",header=TRUE)
lmt.baseline<-lmt[lmt$eventname=="baseline_year_1_arm_1",]
merged.data2 <- merge(merged.data1,lmt.baseline[, c("subjectkey", setdiff(colnames(lmt.baseline),colnames(merged.data1)))],by="subjectkey")
ravlt<-read.table("/Users/ariellekeller/Documents/Kellernet_PrelimAnalysis/Thomp/abcd_ps01.txt",header=TRUE)
ravlt.baseline<-ravlt[ravlt$eventname=="baseline_year_1_arm_1",]
merged.data3 <- merge(merged.data2,ravlt.baseline[, c("subjectkey", setdiff(colnames(ravlt.baseline),colnames(merged.data2)))],by="subjectkey")
trauma<-read.table("/Users/ariellekeller/Documents/Kellernet_PrelimAnalysis/Strife/abcd_ptsd01.txt",header=TRUE)
trauma.baseline<-trauma[trauma$eventname=="baseline_year_1_arm_1",]
combined.data <- merge(merged.data3,trauma.baseline[, c("subjectkey", setdiff(colnames(trauma.baseline),colnames(merged.data3)))],by="subjectkey")
```


# Organize behavioral data
```{r}
# Coerce data types
combined.data$nihtbx_flanker_uncorrected <- as.numeric(combined.data$nihtbx_flanker_uncorrected)
combined.data$nihtbx_picvocab_uncorrected <- as.numeric(combined.data$nihtbx_picvocab_uncorrected)
combined.data$nihtbx_list_uncorrected <- as.numeric(combined.data$nihtbx_list_uncorrected)
combined.data$nihtbx_pattern_uncorrected <- as.numeric(combined.data$nihtbx_pattern_uncorrected)
combined.data$nihtbx_cardsort_uncorrected <- as.numeric(combined.data$nihtbx_cardsort_uncorrected)
combined.data$nihtbx_picture_uncorrected <- as.numeric(combined.data$nihtbx_picture_uncorrected)
combined.data$nihtbx_reading_uncorrected <- as.numeric(combined.data$nihtbx_reading_uncorrected)
combined.data$lmt_scr_perc_correct <- as.numeric(combined.data$lmt_scr_perc_correct)
combined.data$pea_ravlt_sd_trial_i_tc <- as.numeric(combined.data$pea_ravlt_sd_trial_i_tc)
combined.data$pea_ravlt_sd_trial_ii_tc <- as.numeric(combined.data$pea_ravlt_sd_trial_ii_tc)
combined.data$pea_ravlt_sd_trial_iii_tc <- as.numeric(combined.data$pea_ravlt_sd_trial_iii_tc)
combined.data$pea_ravlt_sd_trial_iv_tc <- as.numeric(combined.data$pea_ravlt_sd_trial_iv_tc)
combined.data$pea_ravlt_sd_trial_v_tc <- as.numeric(combined.data$pea_ravlt_sd_trial_v_tc)
combined.data$interview_age <- as.numeric(combined.data$interview_age)

ind_pea_ravlt = c(which(names(combined.data)=="pea_ravlt_sd_trial_i_tc"),which(names(combined.data)=="pea_ravlt_sd_trial_ii_tc"),
	which(names(combined.data)=="pea_ravlt_sd_trial_iii_tc"),which(names(combined.data)=="pea_ravlt_sd_trial_iv_tc"),
	which(names(combined.data)=="pea_ravlt_sd_trial_v_tc")); names(combined.data)[ind_pea_ravlt]; summary(combined.data[,ind_pea_ravlt])
combined.data$pea_ravlt_ld = apply(combined.data[,ind_pea_ravlt],1,sum)

combined.data$pea_ravlt_ld <- as.numeric(combined.data$pea_ravlt_ld)

# Rename according to Thompson 2018 code
names(combined.data)[which(names(combined.data)=="nihtbx_picvocab_uncorrected")] = "PicVocab"
names(combined.data)[which(names(combined.data)=="nihtbx_flanker_uncorrected")] = "Flanker"
names(combined.data)[which(names(combined.data)=="nihtbx_list_uncorrected")] = "List"
names(combined.data)[which(names(combined.data)=="nihtbx_cardsort_uncorrected")] = "CardSort"
names(combined.data)[which(names(combined.data)=="nihtbx_pattern_uncorrected")] = "Pattern"
names(combined.data)[which(names(combined.data)=="nihtbx_picture_uncorrected")] = "Picture"
names(combined.data)[which(names(combined.data)=="nihtbx_reading_uncorrected")] = "Reading"
names(combined.data)[which(names(combined.data)=="pea_ravlt_ld")] = "RAVLT"
names(combined.data)[which(names(combined.data)=="lmt_scr_perc_correct")] = "LMT"
```


# Remove subjects based on the following criteria:
## 1) 8min of retained TRs (600 TRs)
## 2) ABCD Booleans for rest and task
```{r}
num_TRs <- read.csv("/Users/ariellekeller/Documents/Kellernet_PrelimAnalysis/num_TRs_by_subj_redo.csv")
data<-merge(combined.data,num_TRs,by="subjectkey")
data.clean<-data[data$numTRs>=600,] # we go from 9,132 to 8,293 at this step

# Remove participants based on booleans from ABCD
abcd_imgincl01 <- read.csv("/Users/ariellekeller/Documents/Kellernet_PrelimAnalysis/abcd_imgincl01.csv")
abcd_imgincl01 <- abcd_imgincl01[abcd_imgincl01$eventnam=="baseline_year_1_arm_1",]
abcd_imgincl01 <- abcd_imgincl01[!abcd_imgincl01$visit=="",] # start here with 11,663 (8,287 of the 9,132 set)
abcd_imgincl01 <- abcd_imgincl01[abcd_imgincl01$imgincl_t1w_include==1,] # down to 11,124 (8,045 of the 9,132 set)
abcd_imgincl01 <- abcd_imgincl01[abcd_imgincl01$imgincl_rsfmri_include==1,] # down to 9,388 (7,475 of the 9,132 set)
abcd_imgincl01 <- abcd_imgincl01[abcd_imgincl01$imgincl_mid_include==1,] # down to 7,847 (6,344 of the 9,132 set)
abcd_imgincl01 <- abcd_imgincl01[abcd_imgincl01$imgincl_nback_include==1,] # down to 6,348 (5,161 of the 9,132 set)
abcd_imgincl01 <- abcd_imgincl01[abcd_imgincl01$imgincl_sst_include==1,] # down to 5,606 (4,164 of the 9,132 set)

combined.data <- merge(data.clean,abcd_imgincl01[, c("subjectkey",'imgincl_t1w_include')],by="subjectkey")
```


# Calculate Thompson factor scores
```{r}
combined.data$thompson_PC1 <- (0.754*combined.data$PicVocab)+(0.213*combined.data$Flanker)+(0.471*combined.data$List)+(0.205*combined.data$CardSort)+(0.015*combined.data$Pattern)+(0.012*combined.data$Picture)+(0.82*combined.data$Reading)+(0.306*combined.data$RAVLT)+(0.5*combined.data$LMT)

combined.data$thompson_PC2 <- (0.065*combined.data$PicVocab)+(0.712*combined.data$Flanker)+(0.148*combined.data$List)+(0.71*combined.data$CardSort)+(0.813*combined.data$Pattern)+(0.135*combined.data$Picture)+(0.12*combined.data$Reading)+(0.125*combined.data$RAVLT)+(0.299*combined.data$LMT)

combined.data$thompson_PC3 <- (0.19*combined.data$PicVocab)+(0.067*combined.data$Flanker)+(0.493*combined.data$List)+(0.232*combined.data$CardSort)+(0.085*combined.data$Pattern)+(0.863*combined.data$Picture)+(0.122*combined.data$Reading)+(0.712*combined.data$RAVLT)+(0.068*combined.data$LMT)

# Remove outliers
mean_PC1 <- mean(combined.data$thompson_PC1,na.rm=TRUE)
mean_PC2 <- mean(combined.data$thompson_PC2,na.rm=TRUE)
mean_PC3 <- mean(combined.data$thompson_PC3,na.rm=TRUE)
sd3_PC1 <- sd(combined.data$thompson_PC1,na.rm=TRUE)*3
sd3_PC2 <- sd(combined.data$thompson_PC2,na.rm=TRUE)*3
sd3_PC3 <- sd(combined.data$thompson_PC3,na.rm=TRUE)*3
sum(combined.data$thompson_PC1 > mean_PC1+sd3_PC1,na.rm=TRUE) # 8 outliers
sum(combined.data$thompson_PC2 > mean_PC2+sd3_PC2,na.rm=TRUE) # 2 outliers
sum(combined.data$thompson_PC3 > mean_PC3+sd3_PC3,na.rm=TRUE) # 0 outliers
combined.data.noOutliers <- combined.data[combined.data$thompson_PC1>(mean_PC1-sd3_PC1) & combined.data$thompson_PC1<(mean_PC1+sd3_PC1) & combined.data$thompson_PC2>(mean_PC2-sd3_PC2) & combined.data$thompson_PC2<(mean_PC2+sd3_PC2) & combined.data$thompson_PC3>(mean_PC3-sd3_PC3) & combined.data$thompson_PC3<(mean_PC3+sd3_PC3),]
```


# Calculate ACEs variables
```{r}

combined.data.noOutliers[,224:240]<-as.numeric(unlist(combined.data.noOutliers[,224:240]))

# Calculation of subscore with items related to physical and sexual abuse
combined.data.noOutliers$abuse <- rowSums(data.frame(as.numeric(combined.data.noOutliers$ksads_ptsd_raw_761_p),as.numeric(combined.data.noOutliers$ksads_ptsd_raw_762_p),as.numeric(combined.data.noOutliers$ksads_ptsd_raw_763_p),as.numeric(combined.data.noOutliers$ksads_ptsd_raw_767_p),as.numeric(combined.data.noOutliers$ksads_ptsd_raw_768_p),as.numeric(combined.data.noOutliers$ksads_ptsd_raw_769_p)),na.rm=TRUE)

# Calculation of subscore with items related to trauma (car accidents, natural disasters, loss, etc.)
combined.data.noOutliers$trauma <- rowSums(data.frame(as.numeric(combined.data.noOutliers$ksads_ptsd_raw_754_p),as.numeric(combined.data.noOutliers$ksads_ptsd_raw_755_p),as.numeric(combined.data.noOutliers$ksads_ptsd_raw_756_p),as.numeric(combined.data.noOutliers$ksads_ptsd_raw_757_p),as.numeric(combined.data.noOutliers$ksads_ptsd_raw_758_p),as.numeric(combined.data.noOutliers$ksads_ptsd_raw_759_p),as.numeric(combined.data.noOutliers$ksads_ptsd_raw_760_p),as.numeric(combined.data.noOutliers$ksads_ptsd_raw_766_p),as.numeric(combined.data.noOutliers$ksads_ptsd_raw_770_p)),na.rm=TRUE)

# Remember to add in this variable about family structure so we can use it as a covariate
family <-read.table("/Users/ariellekeller/Documents/Kellernet_PrelimAnalysis/ses/acspsw03.txt",header=TRUE)
family.baseline<-family[family$eventname=="baseline_year_1_arm_1",]
abcd.data <- merge(combined.data.noOutliers,family.baseline[, c("subjectkey", setdiff(colnames(family.baseline),colnames(combined.data.noOutliers)))],by="subjectkey")

emo.neglect <-read.table("/Users/ariellekeller/Documents/Kellernet_PrelimAnalysis/neglect/crpbi01.txt",header=TRUE)
emo.neglect.baseline<-emo.neglect[emo.neglect$eventname=="baseline_year_1_arm_1",]
phy.neglect <-read.table("/Users/ariellekeller/Documents/Kellernet_PrelimAnalysis/neglect/pmq01.txt",header=TRUE)
phy.neglect.baseline<-phy.neglect[phy.neglect$eventname=="baseline_year_1_arm_1",]
neglect.data <- merge(emo.neglect.baseline,phy.neglect.baseline[, c("subjectkey", setdiff(colnames(phy.neglect.baseline),colnames(emo.neglect.baseline)))],by="subjectkey")

abcd.data<-merge(abcd.data,neglect.data[,c("subjectkey", setdiff(colnames(neglect.data),colnames(abcd.data)))],by="subjectkey")

# Calculate subscales of deprivation (emotional and physical neglect) - see this ref for motivation https://www.sciencedirect.com/science/article/pii/S2352289518300821
abcd.data$acceptance <- rowSums(data.frame(as.numeric(abcd.data$crpbi_parent1_y),as.numeric(abcd.data$crpbi_parent2_y),as.numeric(abcd.data$crpbi_parent3_y),as.numeric(abcd.data$crpbi_parent4_y),as.numeric(abcd.data$crpbi_parent5_y)))

abcd.data$monitoring <- rowSums(data.frame(as.numeric(abcd.data$parent_monitor_q1_y),as.numeric(abcd.data$parent_monitor_q2_y),as.numeric(abcd.data$parent_monitor_q3_y),as.numeric(abcd.data$parent_monitor_q4_y),as.numeric(abcd.data$parent_monitor_q5_y)))

abcd.data$abuse.binary <- factor(abcd.data$abuse>=1,labels = c("No Abuse","Abuse"))
abcd.data$abuse.binary.numeric <- as.numeric(abcd.data$abuse.binary)
abcd.data$trauma.binary <- factor(abcd.data$trauma>=1,labels = c("No Trauma","Trauma"))
abcd.data$trauma.binary.numeric <- as.numeric(abcd.data$trauma.binary)

median.monitoring = median(na.omit(abcd.data$monitoring))
median.acceptance = median(na.omit(abcd.data$acceptance))
abcd.data$monitoring.binary <- factor(abcd.data$monitoring<20,labels = c("Low Physical Neglect","High Physical Neglect"))
abcd.data$monitoring.binary.numeric <- as.numeric(abcd.data$monitoring.binary)
abcd.data$acceptance.binary <- factor(abcd.data$acceptance<7.5,labels = c("Low Emotional Neglect","High Emotional Neglect"))
abcd.data$acceptance.binary.numeric <- as.numeric(abcd.data$acceptance.binary)



# calculate a total FPN score
combined.data.noOutliers$totalFPN <- rowSums(data.frame(as.numeric(combined.data.noOutliers$df4),as.numeric(combined.data.noOutliers$df16),as.numeric(combined.data.noOutliers$df18)))


# separate train and test sets
trainIDs <- read.csv("/Users/ariellekeller/Documents/Kellernet_PrelimAnalysis/train.csv")
train.data <- merge(combined.data.noOutliers,trainIDs,by="subjectkey") # n=2,149
test.data <- combined.data.noOutliers[!is.element(combined.data.noOutliers$subjectkey,trainIDs$subjectkey),] #n=2,424
```



# Run some models!
```{r}

```

